name: Gerar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Extrair projeto
        run: |
          mkdir projeto
          unzip -q Libris_Geracao_Android_Studio.zip -d projeto

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Gerar APK
        run: |
          PROJECT_DIR=$(dirname "$(find projeto -type f \( -name settings.gradle -o -name settings.gradle.kts \) | head -n 1)")
          cd "$PROJECT_DIR"
          gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Libris-Geracao-APK
          path: projeto/**/build/outputs/apk/**/*.apk
